apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
        - name: hotel-frontend
          image: hotel-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-frontend
spec:
  type: ClusterIP
  selector:
    app: hotel-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP